module.exports = [
  // SYLHET DIVISION (4 Districts)
  {
    id: 'sylhet',
    divisionId: 'sylhet',
    name: 'Sylhet',
    nameBn: '?????',
    hq: 'Sylhet',
    area: '3,490 km²',
    population: '3.9 Million',
    rivers: ['Surma', 'Kushiyara', 'Piyain', 'Sari-Goyain'],
    landmarks: ['Hazrat Shah Jalal (R.) Dargah', 'Hazrat Shah Paran (R.) Shrine', 'Keane Bridge & Ali Amjad Clock', 'Ratargul Swamp Forest', 'Jaflong River & Stone Valley', 'Bholaganj Sada Pathor', 'Bisnakandi'],
    delicacy: 'Sylheti Shatkora Beef, Nunor Bora, Bakarkhani, Fresh Assam-Ceylon Black Tea',
    heritage: '1303 arrival of Sufi saint Hazrat Shah Jalal (R.); spiritual gateway of South Asia and highest remittance-earning region.',
    touristTips: 'Take a serene country boat into the submerged mangrove-like canopy of Ratargul Freshwater Swamp Forest.'
  },
  {
    id: 'moulvibazar',
    divisionId: 'sylhet',
    name: 'Moulvibazar',
    nameBn: '??????????',
    hq: 'Moulvibazar',
    area: '2,799 km²',
    population: '2.1 Million',
    rivers: ['Manu', 'Dhalai', 'Kushiyara'],
    landmarks: ['Sreemangal Tea Estates (Tea Capital)', 'Lawachara National Park (Hoolock Gibbon Sanctuary)', 'Madhabkunda Waterfall', 'Baikka Beel Bird Sanctuary', 'Hum Hum Waterfall'],
    delicacy: 'Nilkantha Seven Layer Tea, Manipuri Pitha, Pineapples',
    heritage: 'Produces 75%+ of Bangladesh tea; pristine evergreen rainforests with endangered wildlife at Lawachara.',
    touristTips: 'Taste world-famous 7-colored multi-layered tea at Nilkantha Tea Cabin and trek through Lawachara jungle canopy.'
  },
  {
    id: 'habiganj',
    divisionId: 'sylhet',
    name: 'Habiganj',
    nameBn: '???????',
    hq: 'Habiganj',
    area: '2,637 km²',
    population: '2.3 Million',
    rivers: ['Khowai', 'Kushiyara', 'Kalni', 'Sutang'],
    landmarks: ['Satchari National Park', 'Rema-Kalenga Wildlife Sanctuary', 'Baniachong (Largest Village in Asia)', 'Shankar Pasha Shahi Mosque'],
    delicacy: 'Haor Boro Fish Curry, Handloom Manipuri Shawls',
    heritage: 'Baniachong holds the distinction of being the largest village in Asia; Rema-Kalenga is the second largest natural forest in Bangladesh.',
    touristTips: 'Walk the tree canopy trail inside Satchari National Park to spot rare birds and capped langurs.'
  },
  {
    id: 'sunamganj',
    divisionId: 'sylhet',
    name: 'Sunamganj',
    nameBn: '?????????',
    hq: 'Sunamganj',
    area: '3,670 km²',
    population: '2.7 Million',
    rivers: ['Surma', 'Jadukata', 'Rakti', 'Baulai'],
    landmarks: ['Tanguar Haor (UNESCO Ramsar Site)', 'Jadukata River & Barek Tila', 'Shimul Bagan (Red Cotton Flower Forest)', 'Hason Raja Palace Museum'],
    delicacy: 'Freshwater Haor Fish (Airh, Chital, Baim), Sunamganjer Sandesh',
    heritage: 'Homeland of mystic philosopher songwriter Hason Raja and Baul king Shah Abdul Karim; Tanguar Haor is a global Ramsar biodiversity wetland.',
    touristTips: 'Book a luxury wooden houseboat on Tanguar Haor for overnight starlight cruising and swim in turquoise Jadukata river.'
  },

  // BARISHAL DIVISION (6 Districts)
  {
    id: 'barishal',
    divisionId: 'barishal',
    name: 'Barishal',
    nameBn: '??????',
    hq: 'Barishal',
    area: '2,785 km²',
    population: '2.5 Million',
    rivers: ['Kirtankhola', 'Arial Khan', 'Tetulia', 'Sandhya'],
    landmarks: ['Bhimruli Floating Guava Market', 'Bells Park (Bangabandhu Udyan)', 'Oxford Mission Church (1903 Epiphany)', 'Durga Sagar Dighi', 'BM College Heritage Campus'],
    delicacy: 'Ilish Fish Mustard Jhol, Balam Rice, Sweet Amra (Hog Plum), Gournadir Doi',
    heritage: 'Referred to historically as the Venice of Bengal; homeland of poet Jibanananda Das (author of Banalata Sen) and Sher-e-Bangla A.K. Fazlul Huq.',
    touristTips: 'Embark on an iconic multi-deck overnight launch journey from Dhaka to Barishal across the illuminated river highways.'
  },
  {
    id: 'bhola',
    divisionId: 'barishal',
    name: 'Bhola',
    nameBn: '????',
    hq: 'Bhola',
    area: '3,403 km²',
    population: '1.9 Million',
    rivers: ['Meghna', 'Tetulia', 'Ilisha'],
    landmarks: ['Jacob Tower (Char Fasson 225-ft Viewpoint)', 'Monpura Island (Untouched Coastal Pearl)', 'Kukri Mukri Island Deer Sanctuary', 'Tazul Islam Eco Park'],
    delicacy: 'Bhola Buffalo Milk Curd (Moish Doi), Meghna Coastal Hilsa, Fresh Coconut',
    heritage: 'The only island district of Bangladesh and largest offshore delta island; blessed with colossal natural gas reserves.',
    touristTips: 'Ride the high-speed glass elevator of 225-foot Jacob Tower to overlook the vast green island landscapes and sea channels.'
  },
  {
    id: 'patuakhali',
    divisionId: 'barishal',
    name: 'Patuakhali',
    nameBn: '?????????',
    hq: 'Patuakhali',
    area: '3,221 km²',
    population: '1.7 Million',
    rivers: ['Payra', 'Andharmanik', 'Lauhati', 'Lalua'],
    landmarks: ['Kuakata Sea Beach (Sagor Kannya)', 'Fatrar Bon (Sundarbans Extension)', 'Payra Deep Seaport', 'Rakhine Indigenous Seema Temple', 'Kuakata Buddhist Well'],
    delicacy: 'Crab Curry, Coral Fish Fry, Coconut Water, Pitha',
    heritage: 'Kuakata offers the rare panoramic spectacle of watching both sunrise and sunset over the sparkling Bay of Bengal from the same beach spot.',
    touristTips: 'Wake up before dawn to watch the sunrise at Gangamati point and rent a beach bike along the 18 km sand stretch.'
  },
  {
    id: 'pirojpur',
    divisionId: 'barishal',
    name: 'Pirojpur',
    nameBn: '????????',
    hq: 'Pirojpur',
    area: '1,308 km²',
    population: '1.2 Million',
    rivers: ['Baleshwar', 'Damodar', 'Kocha', 'Sandhya'],
    landmarks: ['Kuriana Floating Guava Market', 'Swarupkathi Timber Market & Plant Nurseries', 'Rayerkati Zamindar Bari', 'Baleshwar River Bridge'],
    delicacy: 'Sweet Guava, Amra, Sandhya River Prawns',
    heritage: 'Pioneered century-old riverine agricultural canal networks and nursery trading throughout Bangladesh.',
    touristTips: 'Take a country dinghy boat tour through water canals shaded under lush fruit orchards during monsoon.'
  },
  {
    id: 'barguna',
    divisionId: 'barishal',
    name: 'Barguna',
    nameBn: '??????',
    hq: 'Barguna',
    area: '1,831 km²',
    population: '1.0 Million',
    rivers: ['Payra', 'Bishkhali', 'Baleshwar', 'Haringhata'],
    landmarks: ['Shuvo Shondha Sea Beach (Taltali)', 'Haringhata Mangrove Forest', 'Bibichini Shahi Mosque', 'Sonakata Eco Park'],
    delicacy: 'Fresh Coastal Dried Fish, Bagda Shrimp, Coconut Treats',
    heritage: 'Ancient coastal outpost safeguarding southwestern estuaries; pristine mangrove wildlife sanctuary at Haringhata.',
    touristTips: 'Visit Shuvo Shondha beach where Payra river meets the open sea bordered by thick green Casuarina forests.'
  },
  {
    id: 'jhalokati',
    divisionId: 'barishal',
    name: 'Jhalokati',
    nameBn: '???????',
    hq: 'Jhalokati',
    area: '749 km²',
    population: '0.7 Million',
    rivers: ['Sugandha', 'Bishkhali', 'Gabkhan'],
    landmarks: ['Gabkhan Channel (Suez Canal of Bangladesh)', 'Bhimruli Market Point', 'Kirtipasha Zamindar Bari', 'Suchendra Palace'],
    delicacy: 'Shital Pati (Cooling Cane Mats), Jhalokati Sweet Doi, Guava Juice',
    heritage: 'Gabkhan channel is an artificial 18-km river canal built during British era to connect coastal waterway navigation.',
    touristTips: 'Watch huge cargo steamers navigate through the high-span Gabkhan bridge channel.'
  },

  // RANGPUR DIVISION (8 Districts)
  {
    id: 'rangpur',
    divisionId: 'rangpur',
    name: 'Rangpur',
    nameBn: '?????',
    hq: 'Rangpur',
    area: '2,308 km²',
    population: '3.2 Million',
    rivers: ['Teesta', 'Ghaghat', 'Karatoya'],
    landmarks: ['Tajhat Palace (Rangpur Museum)', 'Rangpur Zoo (2nd largest)', 'Chikli Water Park', 'Carmichael College Historic Campus', 'Keramatia Mosque'],
    delicacy: 'Haribhanga Sweet Mango, Rangpur Shatranji Handloom Rugs (GI Tagged), Pitha',
    heritage: 'Royal palace of Maharaja Jagadindra Roy; legendary Shatranji woven carpet craft dating back to Mughal emperor Akbar era.',
    touristTips: 'Marvel at the marble staircase and colonial chandeliers of Tajhat Palace and Carmichael College red-brick campus.'
  },
  {
    id: 'dinajpur',
    divisionId: 'rangpur',
    name: 'Dinajpur',
    nameBn: '????????',
    hq: 'Dinajpur',
    area: '3,438 km²',
    population: '3.3 Million',
    rivers: ['Punarbhaba', 'Atrai', 'Dhepa', 'Karatoya'],
    landmarks: ['Kantaji Temple (Finest Terracotta)', 'Nayabad Mosque', 'Ramsagar National Park (Largest Man-Made Dighi)', 'Dinajpur Rajbari', 'Shopnopuri Park'],
    delicacy: 'Bedana & Madraji Litchi, Fragrant Kataribhog Rice, Papri Sweet',
    heritage: '1752 Kantaji Temple is the most spectacular terracotta Hindu temple in South Asia, decorated with Ramayana illustrations.',
    touristTips: 'Visit Kantaji Temple during sunset to capture the fiery golden glow of its thousands of terracotta relief carvings.'
  },
  {
    id: 'panchagarh',
    divisionId: 'rangpur',
    name: 'Panchagarh',
    nameBn: '??????',
    hq: 'Panchagarh',
    area: '1,405 km²',
    population: '1.1 Million',
    rivers: ['Karatoya', 'Mahananda', 'Dahuk'],
    landmarks: ['Tetulia Kanchenjunga Viewpoint', 'Banglabandha Zero Point & Dry Port', 'Plainland Organic Tea Gardens', 'Mirzapur Shahi Mosque', 'Rocks Museum'],
    delicacy: 'Panchagarh Plainland Organic Tea, River Stone Trout Fish',
    heritage: 'Northernmost tip of Bangladesh; only spot in Bangladesh where Himalayan peak Mt. Kanchenjunga can be viewed with naked eyes.',
    touristTips: 'Visit Tetulia Dak Bungalow in autumn (October-November) on a clear dawn to witness the majestic snow-capped Kanchenjunga.'
  },
  {
    id: 'thakurgaon',
    divisionId: 'rangpur',
    name: 'Thakurgaon',
    nameBn: '?????????',
    hq: 'Thakurgaon',
    area: '1,810 km²',
    population: '1.5 Million',
    rivers: ['Tangon', 'Kulic', 'Nagor'],
    landmarks: ['Baliadangi 200-yr Ancient Mango Tree (Suryapuri)', 'Jamidar Bari Mosque', 'Ranishankail Rajbari', 'Haripur Rajbari'],
    delicacy: 'Suryapuri Mango, Peda Sweet, River Fish',
    heritage: 'The legendary Suryapuri mango tree at Baliadangi spans over 2 bighas with 19 major root branches.',
    touristTips: 'Stand under the colossal umbrella shade of the 200-year-old Baliadangi ancient heritage mango tree.'
  },
  {
    id: 'nilphamari',
    divisionId: 'rangpur',
    name: 'Nilphamari',
    nameBn: '?????????',
    hq: 'Nilphamari',
    area: '1,581 km²',
    population: '2.0 Million',
    rivers: ['Teesta', 'Jamuneshwari', 'Buri Teesta'],
    landmarks: ['Teesta Barrage (Dalia)', 'Nilsagar Historic Dighi', 'Saidpur Railway Workshop (Subcontinent Oldest 1870)', 'Chini Mosque'],
    delicacy: 'Teesta Fish, Chini Mosque Sweets, Kataribhog Chira',
    heritage: 'Saidpur Railway Workshop is the largest and oldest railway repair facility in Bengal established in 1870.',
    touristTips: 'Tour the dazzling China-porcelain tiled Chini Mosque in Saidpur with 27 minarets.'
  },
  {
    id: 'kurigram',
    divisionId: 'rangpur',
    name: 'Kurigram',
    nameBn: '?????????',
    hq: 'Kurigram',
    area: '2,246 km²',
    population: '2.3 Million',
    rivers: ['Brahmaputra', 'Dharla', 'Teesta', 'Dudhkumar'],
    landmarks: ['Chilmari Port & Riverfront', 'Dharla Bridge', 'Shahi Mosque of Forkerhat', 'Dasherhat Zamindar Bari'],
    delicacy: 'Brahmaputra River Boal Fish, Kheer Chomchom, Chilmari Pitha',
    heritage: 'Immortalized in legendary folk songs such as Oki Gariyal Bhai on the historic Chilmari river ghat.',
    touristTips: 'Take a boat trip across the wide expanse of the Brahmaputra River during golden hour.'
  },
  {
    id: 'lalmonirhat',
    divisionId: 'rangpur',
    name: 'Lalmonirhat',
    nameBn: '??????????',
    hq: 'Lalmonirhat',
    area: '1,241 km²',
    population: '1.4 Million',
    rivers: ['Teesta', 'Dharla', 'Saniazan'],
    landmarks: ['Tin Bigha Corridor', 'Burimari Land Port & Zero Point', 'Mogolhat Historic Railway Station', 'Tushbhandar Zamindar Bari'],
    delicacy: 'Corn Dishes, Teesta Fresh Fish, Sweet Sandesh',
    heritage: 'Strategic enclave corridor Tin Bigha; heritage railway junction connecting pre-partition Assam-Bengal rail routes.',
    touristTips: 'Visit the historic Tin Bigha Corridor and Burimari border landscape.'
  },
  {
    id: 'gaibandha',
    divisionId: 'rangpur',
    name: 'Gaibandha',
    nameBn: '?????????',
    hq: 'Gaibandha',
    area: '2,179 km²',
    population: '2.6 Million',
    rivers: ['Brahmaputra', 'Teesta', 'Ghaghat', 'Karatoya'],
    landmarks: ['Balashighat River Terminal', 'Naldanga Zamindar Palace', 'Ghaghat River Green Walkway', 'Karatoya Barrage'],
    delicacy: 'Gaibandhar Roshmonjuri (Signature Reduced Milk Sweet), River Ilish',
    heritage: 'Pioneered river char community development and world-famous Roshmonjuri milk sweet craft.',
    touristTips: 'Taste authentic hot Roshmonjuri sweet prepared in earthen pans in Gaibandha town.'
  },

  // MYMENSINGH DIVISION (4 Districts)
  {
    id: 'mymensingh',
    divisionId: 'mymensingh',
    name: 'Mymensingh',
    nameBn: '????????',
    hq: 'Mymensingh',
    area: '4,395 km²',
    population: '5.8 Million',
    rivers: ['Old Brahmaputra', 'Bhogai', 'Bajua'],
    landmarks: ['Shashi Lodge (Mymensingh Rajbari)', 'Bangladesh Agricultural University (BAU)', 'Zainul Abedin Art Gallery & Park', 'Muktagacha Zamindar Bari', 'Ananda Mohan College', 'Alexander Castle'],
    delicacy: 'Muktagachar Monda (200-year-old Ramgopal Sweet), Malaikari, Fresh Brahmaputra River Fish',
    heritage: 'Maimansingha Gitika medieval folk ballads compiled by Dinesh Chandra Sen; premier agricultural science research in Asia.',
    touristTips: 'Taste authentic GI-famed Monda at Muktagacha Gopal Pal heritage shop and stroll through Shashi Lodge Venus marble gardens.'
  },
  {
    id: 'jamalpur',
    divisionId: 'mymensingh',
    name: 'Jamalpur',
    nameBn: '????????',
    hq: 'Jamalpur',
    area: '2,115 km²',
    population: '2.5 Million',
    rivers: ['Old Brahmaputra', 'Jamuna', 'Jhinai'],
    landmarks: ['Nakshi Kantha Handicraft Villages', 'Hazrat Shah Jamal (R.) Shrine', 'Gandhi Ashram', 'Mellandha Eco Park'],
    delicacy: 'Milir Pitha, Jamalpur Nakshi Pitha, Chhanar Polao Sweet',
    heritage: 'World famous artisan hub of intricate Nakshi Kantha hand-embroidered quilts and mustard oil.',
    touristTips: 'Visit rural artisan cooperatives in Islampur to see women craft exquisite Nakshi Kantha needlework.'
  },
  {
    id: 'netrokona',
    divisionId: 'mymensingh',
    name: 'Netrokona',
    nameBn: '?????????',
    hq: 'Netrokona',
    area: '2,794 km²',
    population: '2.4 Million',
    rivers: ['Kangsha', 'Someshwari', 'Dhanu', 'Magra'],
    landmarks: ['Birishiri & Ceramic White Clay Lake (Durgapur)', 'Someshwari River & Garo Hills', 'Ranikhong Catholic Mission', 'Hazrat Shah Sultan Kamaruddin Shrine'],
    delicacy: 'Balish Mishti of Goyanath (Pillow Sweet), Haor Fish, Someshwari Mahseer',
    heritage: 'Land of Baul songs and Hajong tribal revolution lead by Comrade Moni Singh; turquoise mineral lakes at Birishiri.',
    touristTips: 'Ride an engine boat on crystal clear Someshwari River and photograph the turquoise water of Ceramic White Clay Lake in Durgapur.'
  },
  {
    id: 'sherpur',
    divisionId: 'mymensingh',
    name: 'Sherpur',
    nameBn: '??????',
    hq: 'Sherpur',
    area: '1,364 km²',
    population: '1.5 Million',
    rivers: ['Brahmaputra', 'Bhogai', 'Chelakhali', 'Someshwari'],
    landmarks: ['Ghazni Leisure Center (Garo Hill Foot)', 'Madhutila Eco Park', 'Maisaheba Mosque', 'Garo Indigenous Heritage Village'],
    delicacy: 'Chhana Sandesh, Wild Garo Honey, Sticky Fragrant Biruin Rice',
    heritage: 'Bordered by lush Meghalaya hills with rich Koch and Garo indigenous customs; historical kingdom of Sher Ali Ghazi.',
    touristTips: 'Climb the watchtower at Madhutila Eco Park for a panoramic view of the rolling green Garo Hills along the border.'
  }
];
