module.exports = [
  // DHAKA DIVISION (13 Districts)
  {
    id: 'dhaka',
    divisionId: 'dhaka',
    name: 'Dhaka',
    nameBn: '????',
    hq: 'Dhaka',
    area: '1,463 km²',
    population: '14.7 Million',
    rivers: ['Buriganga', 'Turag', 'Dhaleshwari', 'Balu'],
    landmarks: ['Ahsan Manzil', 'Lalbagh Fort', 'Tara Masjid', 'Curzon Hall', 'Jatiya Sangsad Bhaban', 'Dhakeshwari Temple'],
    delicacy: 'Dhakaiya Biryani, Bakarkhani, Morog Polao',
    heritage: 'Mughal Capital Jahangirnagar (1610), 1952 Language Movement, 1971 Independence Proclamation at Historic Suhrawardy Udyan.',
    touristTips: 'Explore Old Dhaka heritage trails on a rickshaw, visit Sadarghat launch terminal at sunset, and taste authentic saffron biryani.'
  },
  {
    id: 'gazipur',
    divisionId: 'dhaka',
    name: 'Gazipur',
    nameBn: '???????',
    hq: 'Gazipur',
    area: '1,806 km²',
    population: '3.4 Million',
    rivers: ['Turag', 'Balu', 'Shitalakshya', 'Banshir'],
    landmarks: ['Bhawal National Park', 'Bangabandhu Safari Park', 'Bhawal Rajbari', 'DUET Campus'],
    delicacy: 'Jackfruit (National Fruit of Bangladesh), Traditional Pitha',
    heritage: 'Historic Bhawal Estate and famous Sannyasi case; premier research institutions and digital industrial hub.',
    touristTips: 'Visit Bangabandhu Safari Park for open safari jeep rides and Bhawal Sal forest for eco-resort retreats.'
  },
  {
    id: 'narayanganj',
    divisionId: 'dhaka',
    name: 'Narayanganj',
    nameBn: '??????????',
    hq: 'Narayanganj',
    area: '684 km²',
    population: '3.0 Million',
    rivers: ['Shitalakshya', 'Meghna', 'Dhaleshwari'],
    landmarks: ['Panam Nagar (Sonargaon)', 'Sonargaon Folk Art Museum', 'Hajiganj Fort', 'Sonakanda Fort'],
    delicacy: 'Sonargaon Jamdani Weave Heritage Sweets, Jhal Chhola',
    heritage: 'Ancient medieval capital of Bengal under Isa Khan; world capital of UNESCO-inscribed Jamdani handloom.',
    touristTips: 'Walk through the eerie 19th-century deserted colonial mansions of Panam City and visit Shilpacharya Zainul Abedin Folk Art Museum.'
  },
  {
    id: 'tangail',
    divisionId: 'dhaka',
    name: 'Tangail',
    nameBn: '????????',
    hq: 'Tangail',
    area: '3,414 km²',
    population: '3.8 Million',
    rivers: ['Jamuna', 'Dhaleshwari', 'Bangshi', 'Lohajang'],
    landmarks: ['201 Dome Mosque (Gopalpur)', 'Mohera Zamindar Bari', 'Pakutia Zamindar Bari', 'Atiya Mosque'],
    delicacy: 'Porabarir Chamcham (King of Sweets), Tangail Taant Cotton Shari',
    heritage: 'Birthplace of historic Tangail Taant weaving and authentic 1608 Atiya Mosque depicted on 10 Taka note.',
    touristTips: 'Tour Mohera Zamindar Palace heritage resort and buy genuine GI-tagged Tangail handloom cotton saris from local weavers.'
  },
  {
    id: 'munshiganj',
    divisionId: 'dhaka',
    name: 'Munshiganj (Bikrampur)',
    nameBn: '?????????? (?????????)',
    hq: 'Munshiganj',
    area: '1,004 km²',
    population: '1.6 Million',
    rivers: ['Padma', 'Meghna', 'Dhaleshwari', 'Ichamati'],
    landmarks: ['Padma Bridge North Point (Mawa)', 'Idrakpur Fort', 'Baba Adam Mosque', 'Bikrampur Museum', 'Atish Dipankar Birthplace'],
    delicacy: 'Bikrampuri Sweet Curd, Mawa Ghat Fresh Fried Ilish with Mustard & Green Chilies',
    heritage: 'Ancient capital of Bikrampur Kings; birthplace of Buddhist master Atish Dipankar and scientist Sir Jagadish Chandra Bose.',
    touristTips: 'Drive across the Mawa expressway to enjoy fresh sizzling Padma Ilish fish fries right at the river pier.'
  },
  {
    id: 'narsingdi',
    divisionId: 'dhaka',
    name: 'Narsingdi',
    nameBn: '???????',
    hq: 'Narsingdi',
    area: '1,150 km²',
    population: '2.2 Million',
    rivers: ['Meghna', 'Old Brahmaputra', 'Shitalakshya'],
    landmarks: ['Wari-Bateshwar Archaeological Site (2500-year-old)', 'Bir Sreshtho Matiur Rahman Museum', 'Dream Holiday Park'],
    delicacy: 'Amriti Sweet, Sagar Kola (Banana), Lal Teer Vegetables',
    heritage: 'Wari-Bateshwar, ancient 6th century BCE urban civilization trading across the Indian Ocean.',
    touristTips: 'Discover ancient silver punch-marked coins and Roman glass beads at Wari-Bateshwar excavation center.'
  },
  {
    id: 'manikganj',
    divisionId: 'dhaka',
    name: 'Manikganj',
    nameBn: '?????????',
    hq: 'Manikganj',
    area: '1,383 km²',
    population: '1.4 Million',
    rivers: ['Padma', 'Jamuna', 'Dhaleshwari', 'Kaliganga'],
    landmarks: ['Baliati Palace', 'Teota Zamindar Bari', 'Aricha Ghat'],
    delicacy: 'Hajar Gur (Legendary Date Palm Jaggery), Makhan Peda',
    heritage: 'Baliati Palace is one of the grandest 19th-century zamindar estates in South Asia with 200+ ornate rooms.',
    touristTips: 'Marvel at the seven colossal buildings and ionic columns of Baliati Palace in Saturia.'
  },
  {
    id: 'faridpur',
    divisionId: 'dhaka',
    name: 'Faridpur',
    nameBn: '???????',
    hq: 'Faridpur',
    area: '2,052 km²',
    population: '2.0 Million',
    rivers: ['Padma', 'Kumar', 'Madhumati', 'Arial Khan'],
    landmarks: ['Jasminuddin Ancestral Home (Polli Kobi)', 'Kanaipur Zamindar Bari', 'Faridpur River Jetty'],
    delicacy: 'Khejurer Gur (Date Palm Syrup), Sandesh',
    heritage: 'Homeland of National Rural Poet Jasimuddin (author of Nakshi Kanthar Math); historic Faraizi movement.',
    touristTips: 'Visit Jasimuddin folk museum on the banks of Kumar river in Ambikapur during annual Poush mela.'
  },
  {
    id: 'gopalganj',
    divisionId: 'dhaka',
    name: 'Gopalganj',
    nameBn: '?????????',
    hq: 'Gopalganj',
    area: '1,468 km²',
    population: '1.2 Million',
    rivers: ['Madhumati', 'Garai', 'Ghagar', 'Horkhal'],
    landmarks: ['Bangabandhu Mausoleum Complex (Tungipara)', 'Ulpur Zamindar Bari', 'Orakandi Thakur Bari'],
    delicacy: 'Mattha, Rosogolla, Chhana Sweets',
    heritage: 'Sacred birthplace and eternal resting place of the Father of the Nation Bangabandhu Sheikh Mujibur Rahman.',
    touristTips: 'Pay respects at the tranquil red-brick and white marble Bangabandhu Mausoleum Complex in Tungipara.'
  },
  {
    id: 'madaripur',
    divisionId: 'dhaka',
    name: 'Madaripur',
    nameBn: '?????????',
    hq: 'Madaripur',
    area: '1,125 km²',
    population: '1.2 Million',
    rivers: ['Padma', 'Arial Khan', 'Kumar'],
    landmarks: ['Shakuni Lake & Park', 'Mithapur Zamindar Bari', 'Khatal Bari Ghat'],
    delicacy: 'Kashmiri Sweet, Khejur Patali Gur',
    heritage: 'Named after Sufi Saint Badiuddin Zinda Shah Madar; key hub during anti-British Faraizi resistance led by Haji Shariatullah.',
    touristTips: 'Stroll around the scenic Shakuni Lake walkway in the heart of Madaripur town.'
  },
  {
    id: 'rajbari',
    divisionId: 'dhaka',
    name: 'Rajbari',
    nameBn: '???????',
    hq: 'Rajbari',
    area: '1,099 km²',
    population: '1.0 Million',
    rivers: ['Padma', 'Garai', 'Chitra', 'Kumar'],
    landmarks: ['Mir Mosharraf Hossain Memorial Center (Baliakandi)', 'Daulatdia River Confluence', 'Godadar Rail Bridge'],
    delicacy: 'Rajbari Chamcham, Padma River Hilsa',
    heritage: 'Homeland of legendary novelist Mir Mosharraf Hossain, author of timeless masterpiece Bishad Shindhu.',
    touristTips: 'Visit Mir Mosharraf Hossain auditorium and memorial library in Padamdi.'
  },
  {
    id: 'shariatpur',
    divisionId: 'dhaka',
    name: 'Shariatpur',
    nameBn: '?????????',
    hq: 'Shariatpur',
    area: '1,174 km²',
    population: '1.2 Million',
    rivers: ['Padma', 'Meghna', 'Kirtinasha', 'Arial Khan'],
    landmarks: ['Padma Bridge South Approach (Janjira)', 'Fatehabad Zamindar Bari', 'Burirhat Mosque'],
    delicacy: 'Hilsa from Kirtinasha, Date Jaggery Sandesh',
    heritage: 'Named in honor of Haji Shariatullah, pioneer of 19th-century socio-religious Faraizi renaissance.',
    touristTips: 'Experience the modern mega expressway connecting Janjira directly with Padma Bridge.'
  },
  {
    id: 'kishoreganj',
    divisionId: 'dhaka',
    name: 'Kishoreganj',
    nameBn: '?????????',
    hq: 'Kishoreganj',
    area: '2,731 km²',
    population: '3.1 Million',
    rivers: ['Old Brahmaputra', 'Meghna', 'Dhanu', 'Baulai'],
    landmarks: ['Nikli Haor Waterfront & All-Weather Road', 'Pagla Mosque', 'Isha Khan Junglebari Fort', 'Chandravati Shiva Temple'],
    delicacy: 'Haor Fresh Baim & Boal Fish, Kishorganj Balish Mishti (Pillow Sweet)',
    heritage: 'Birthplace of Chandravati (Bengali literature first woman poet) and Satyajit Ray grandfather Upendrakishore Ray Chowdhury.',
    touristTips: 'Rent a traditional engine boat on Nikli Haor during monsoon to feel like cruising on an endless ocean.'
  },

  // CHATTOGRAM DIVISION (11 Districts)
  {
    id: 'chattogram',
    divisionId: 'chattogram',
    name: 'Chattogram',
    nameBn: '?????????',
    hq: 'Chattogram',
    area: '5,282 km²',
    population: '9.2 Million',
    rivers: ['Karnaphuli', 'Halda', 'Sangu', 'Feni'],
    landmarks: ['Chattogram Port', 'Patenga Sea Beach', 'Bangabandhu Sheikh Mujibur Rahman Tunnel', 'Bayejid Bostami Shrine', 'Foys Lake', 'World War II Cemetery'],
    delicacy: 'Mezban Beef Gosht, Kala Bhuna, Chonakatha Shutki Bhorta',
    heritage: 'Historic 1930 Chittagong Armoury Raid led by Masterda Surya Sen; sacred Halda River (only natural carp breeding river).',
    touristTips: 'Drive through South Asia first underwater river tunnel and enjoy red sunset with crab fry at Patenga beach.'
  },
  {
    id: 'coxsbazar',
    divisionId: 'chattogram',
    name: 'Cox\'s Bazar',
    nameBn: '?????????',
    hq: 'Cox\'s Bazar',
    area: '2,491 km²',
    population: '2.8 Million',
    rivers: ['Matamuhuri', 'Bakkhali', 'Naf'],
    landmarks: ['Kolotoli & Laboni Beach', 'Inani Coral Beach', '80-km Marine Drive', 'Saint Martin Coral Island', 'Ramu Buddhist Monasteries', 'Himchari National Park'],
    delicacy: 'Fresh Coral & Red Snapper BBQ, Loitta Fry, Dried Fish (Shutki), Rupchanda Fish Curry',
    heritage: 'World longest unbroken natural sandy beach stretching 120 km; ancient Rakhine Buddhist pagodas in Ramu.',
    touristTips: 'Ride an open-top Jeep down the spectacular Marine Drive highway between crashing ocean waves and emerald green mountains.'
  },
  {
    id: 'rangamati',
    divisionId: 'chattogram',
    name: 'Rangamati',
    nameBn: '??????????',
    hq: 'Rangamati',
    area: '6,116 km²',
    population: '0.65 Million',
    rivers: ['Karnaphuli', 'Kaptai', 'Chengi', 'Maini'],
    landmarks: ['Kaptai Lake', 'Rangamati Hanging Bridge', 'Rajban Vihara', 'Shuvolong Waterfall', 'Chakma Royal Palace'],
    delicacy: 'Bamboo Chicken, Hebaang (Fish Steamed in Banana Leaf), Pajon Curry',
    heritage: 'Spiritual heart of Chakma royalty and indigenous communities; largest artificial freshwater lake in South Asia.',
    touristTips: 'Hire a long-tail boat to navigate through Shuvolong gorge and buy indigenous handmade pinon-hadi fabrics.'
  },
  {
    id: 'bandarban',
    name: 'Bandarban',
    nameBn: '?????????',
    divisionId: 'chattogram',
    hq: 'Bandarban',
    area: '4,479 km²',
    population: '0.45 Million',
    rivers: ['Sangu', 'Matamuhuri', 'Bakkhali'],
    landmarks: ['Nilgiri Resort', 'Thanchi & Nafakhum Waterfall', 'Buddha Dhatu Jadi (Golden Temple)', 'Keokradong & Boga Lake', 'Chimbuk Hill'],
    delicacy: 'Mundhi Indigenous Noodles, Bamboo Shoot Delicacy, Sangu River Mountain Fish',
    heritage: 'Home to 11 diverse ethnic communities (Marma, Bawm, Mro, Tripura, etc.) and Bangladesh highest mountain peaks.',
    touristTips: 'Experience trekking to turquoise crater Boga Lake and sunrise over sea of clouds from Nilgiri top.'
  },
  {
    id: 'khagrachhari',
    name: 'Khagrachhari',
    nameBn: '????????',
    divisionId: 'chattogram',
    hq: 'Khagrachhari',
    area: '2,699 km²',
    population: '0.7 Million',
    rivers: ['Chengi', 'Maini', 'Feni'],
    landmarks: ['Sajek Valley (Ruilui & Konglak Para)', 'Alutila Mysterious Cave', 'Richhang Waterfall', 'Hathikatha Stone Staircase'],
    delicacy: 'Sabrang Herb Curry, Bamboo Shoot Stir-Fry, Wild Forest Honey',
    heritage: 'Traditional Marma and Tripura folk culture; ancient natural limestone sub-terrestrial caves at Alutila.',
    touristTips: 'Walk through the dark limestone Alutila Cave holding a flaming bamboo torch for an adrenaline thrill.'
  },
  {
    id: 'cumilla',
    name: 'Cumilla',
    nameBn: '????????',
    divisionId: 'chattogram',
    hq: 'Cumilla',
    area: '3,085 km²',
    population: '6.2 Million',
    rivers: ['Gumti', 'Meghna', 'Dakatia'],
    landmarks: ['Shalban Vihara (Mainamati)', 'Kotila Mura', 'Cumilla Cantonment War Cemetery', 'Dharmasagar Dighi', 'BARD Campus'],
    delicacy: 'Matri Bhandar Genuine Rasmalai, Khadi Cotton Clothing',
    heritage: '8th-century archaeological center of Buddhist Deva and Chandra dynasties; birthplace of world-renowned hand-spun Khadi cloth.',
    touristTips: 'Buy original Rasmalai directly from historic Matri Bhandar shop at Manoharpur in Cumilla town.'
  },
  {
    id: 'feni',
    name: 'Feni',
    nameBn: '????',
    divisionId: 'chattogram',
    hq: 'Feni',
    area: '928 km²',
    population: '1.6 Million',
    rivers: ['Feni', 'Muhuri', 'Chhagalnaiya'],
    landmarks: ['Muhuri Irrigation Regulator & Dam', 'Bijoy Singh Dighi', 'Chandgazi Mosque', 'Shamsher Gazi Fort'],
    delicacy: 'Feni Mahish Curd (Buffalo Yogurt), Khandaler Mishti',
    heritage: 'Muhuri Project is Bangladesh second largest irrigation project and winter habitat for migratory birds.',
    touristTips: 'Watch sunset where Muhuri and Feni rivers meet the Bay of Bengal estuary.'
  },
  {
    id: 'brahmanbaria',
    name: 'Brahmanbaria',
    nameBn: '??????????????',
    divisionId: 'chattogram',
    hq: 'Brahmanbaria',
    area: '1,927 km²',
    population: '3.3 Million',
    rivers: ['Titas', 'Meghna', 'Buri'],
    landmarks: ['Kalbhairab Temple', 'Ustad Alauddin Khan Ancestral Estate', 'Kailash Tila Gas Field', 'Ashuganj Power Hub'],
    delicacy: 'Chhanar Mukhi Sweet (GI Tagged), Titas River Hilsa',
    heritage: 'Cultural capital of classical music; ancestral land of Sarod maestro Ustad Alauddin Khan and epic novel Titash Ekti Nadir Naam.',
    touristTips: 'Taste authentic melt-in-mouth GI-certified Chhanar Mukhi sweets.'
  },
  {
    id: 'noakhali',
    name: 'Noakhali',
    nameBn: '????????',
    hq: 'Maijdee',
    divisionId: 'chattogram',
    area: '3,685 km²',
    population: '3.6 Million',
    rivers: ['Meghna', 'Dakatia'],
    landmarks: ['Gandhi Ashram (Joyag)', 'Nijhum Dwip Deer Sanctuary', 'Bajra Shahi Mosque', 'Musapur Closer'],
    delicacy: 'Narkel Naru, Chital Fish Kofta, Ghol & Buffalo Curd',
    heritage: 'Mahatma Gandhi peace mission at Joyag during 1946; Nijhum Dwip island home to 40,000+ spotted spotted deer.',
    touristTips: 'Take a boat to Nijhum Dwip to watch herds of wild spotted deer grazing against mangrove forest margins.'
  },
  {
    id: 'lakshmipur',
    name: 'Lakshmipur',
    nameBn: '??????????',
    hq: 'Lakshmipur',
    divisionId: 'chattogram',
    area: '1,455 km²',
    population: '1.9 Million',
    rivers: ['Meghna', 'Dakatia', 'Rahmatkhali'],
    landmarks: ['Tita Khan Jame Mosque', 'Mondal Bari Zamindar Palace', 'Alexander Embankment', 'Kamalnagar Riverfront'],
    delicacy: 'Moish Doi (Buffalo Milk Curd), Supera & Paan',
    heritage: 'Major hub of coastal fish landing, coconut orchards, and fertile alluvial farmland along the Lower Meghna estuary.',
    touristTips: 'Experience traditional fishing boats pulling ashore fresh sparkling silver Hilsa at Motirhat.'
  },
  {
    id: 'chandpur',
    name: 'Chandpur',
    nameBn: '???????',
    hq: 'Chandpur',
    divisionId: 'chattogram',
    area: '1,704 km²',
    population: '2.6 Million',
    rivers: ['Padma', 'Meghna', 'Dakatia'],
    landmarks: ['Mollah Ratan Confluence (Moha Milon)', 'Rupsha Zamindar Bari', 'Haimchar River Estuary', 'Chandpur Launch Terminal'],
    delicacy: 'Chandpur Padma-Meghna Hilsa (Ilish Capital of Bangladesh), One-Minute Mishti',
    heritage: 'Tri-river confluence where the mighty Padma, Meghna, and Dakatia merge together; known globally as the Hilsa Capital.',
    touristTips: 'Visit Mollah Head point at sunset to observe two distinct river water colors mixing together.'
  }
];
