module.exports = [
  // RAJSHAHI DIVISION (8 Districts)
  {
    id: 'rajshahi',
    divisionId: 'rajshahi',
    name: 'Rajshahi',
    nameBn: '???????',
    hq: 'Rajshahi',
    area: '2,407 km²',
    population: '2.9 Million',
    rivers: ['Padma', 'Mahananda', 'Shiba'],
    landmarks: ['Varendra Research Museum', 'Puthia Temple Complex', 'Bagha Mosque', 'Rajshahi University Paris Road', 'Boro Kuthi'],
    delicacy: 'Rajshahi Silk, Himsagar & Langra Mangoes, Kalojam',
    heritage: 'Capital of ancient Varendra civilization; global pioneer of mulberry silk weaving and cleanest green city in Bangladesh.',
    touristTips: 'Stroll along the paved Padma T-Groin embankment at dusk and visit the Varendra research antiquities.'
  },
  {
    id: 'bogura',
    divisionId: 'rajshahi',
    name: 'Bogura',
    nameBn: '?????',
    hq: 'Bogura',
    area: '2,898 km²',
    population: '3.8 Million',
    rivers: ['Karatoya', 'Jamuna', 'Nagar', 'Bangali'],
    landmarks: ['Mahasthangarh (Pundranagar 3rd Century BCE)', 'Govinda Bhita', 'Vasav Vihara', 'Kherua Mosque', 'Gokul Medh (Behula Bashor Ghar)'],
    delicacy: 'Bogra Bogurar Doi (World Famous Sweet Curd), Kotkoti',
    heritage: 'Pundranagar at Mahasthangarh is the earliest fortified urban city site excavated in Bangladesh history.',
    touristTips: 'Climb the ancient ramparts of Mahasthangarh citadel and savor thick baked red curd from Gourogopal or Asian Sweet.'
  },
  {
    id: 'pabna',
    divisionId: 'rajshahi',
    name: 'Pabna',
    nameBn: '?????',
    hq: 'Pabna',
    area: '2,371 km²',
    population: '2.8 Million',
    rivers: ['Padma', 'Jamuna', 'Ichamati'],
    landmarks: ['Hardinge Bridge (Paksey)', 'Rooppur Nuclear Power Plant', 'Jor Bangla Temple', 'Pabna Mental Hospital Heritage Campus'],
    delicacy: 'Pabna Pure Ghee, Peda, Chhanar Jilapi',
    heritage: 'Century-old railway steel truss engineering marvel Hardinge Bridge (1915); home to Bangladesh first nuclear energy plant.',
    touristTips: 'Admire the architectural juxtaposition of historic 1915 Hardinge Bridge and modern Lalon Shah Highway Bridge over the Padma.'
  },
  {
    id: 'sirajganj',
    divisionId: 'rajshahi',
    name: 'Sirajganj',
    nameBn: '?????????',
    hq: 'Sirajganj',
    area: '2,497 km²',
    population: '3.4 Million',
    rivers: ['Jamuna', 'Karatoya', 'Baral', 'Phuljhor'],
    landmarks: ['Bangabandhu Jamuna Bridge', 'Navaratna Temple (Hatikumrul)', 'Rabindra Complex (Shahzadpur)', 'Eliot Bridge'],
    delicacy: 'Sirajganj Milk Sweets, Dhaner Shish Doi, Handloom Cotton Gamchha & Lungi',
    heritage: 'Rabindranath Tagore spent years at Shahzadpur Kachharibari writing iconic poems like Sonar Tari and Postmaster.',
    touristTips: 'Tour the serene Tagore memorial palace at Shahzadpur and admire the 9-towered Navaratna terracotta temple.'
  },
  {
    id: 'natore',
    divisionId: 'rajshahi',
    name: 'Natore',
    nameBn: '?????',
    hq: 'Natore',
    area: '1,896 km²',
    population: '1.9 Million',
    rivers: ['Baral', 'Nagar', 'Atrai'],
    landmarks: ['Uttara Ganabhaban (Dighapatia Rajbari)', 'Rani Bhabani Rajbari', 'Chalan Beel (largest wetland of north)'],
    delicacy: 'Natore Kachagolla (GI Tagged King of Sweet Chhana)',
    heritage: 'Historic capital of Maharani Bhabani who ruled Bengal during 18th century; grand Italian-styled Uttara Ganabhaban palace.',
    touristTips: 'Walk through the 41-acre royal gardens and deer enclosures of Uttara Ganabhaban and taste fresh warm Kachagolla.'
  },
  {
    id: 'naogaon',
    divisionId: 'rajshahi',
    name: 'Naogaon',
    nameBn: '?????',
    hq: 'Naogaon',
    area: '3,435 km²',
    population: '2.8 Million',
    rivers: ['Atrai', 'Punarbhaba', 'Chhoto Jamuna'],
    landmarks: ['Somapura Mahavihara at Paharpur (UNESCO World Heritage)', 'Kushumba Mosque', 'Dubalhati Rajbari', 'Patisar Rabindra Kachharibari'],
    delicacy: 'Pera Sandesh, Fragrant Chinigura Aromatic Rice',
    heritage: '8th-century Somapura Mahavihara built by King Dharmapala is the largest Buddhist vihara south of the Himalayas.',
    touristTips: 'Spend a quiet afternoon exploring the massive central stupa and terracotta plaques of Paharpur UNESCO heritage site.'
  },
  {
    id: 'chapai_nawabganj',
    divisionId: 'rajshahi',
    name: 'Chapai Nawabganj',
    nameBn: '??????????????',
    hq: 'Chapai Nawabganj',
    area: '1,702 km²',
    population: '1.8 Million',
    rivers: ['Padma', 'Mahananda', 'Pagla'],
    landmarks: ['Choto Sona Mosque (Gaur)', 'Darasbari Mosque & Madrasa', 'Tohakhana Palace & Shrine', 'Mahananda Riverfront'],
    delicacy: 'Fazli & Ashwina Mangoes, Shivganjer Chomchom, Kalaikari Ruti with Duck Curry',
    heritage: 'Medieval Sultanate capital of Gaur situated along the western frontier; undisputed Mango Capital of Bangladesh.',
    touristTips: 'Visit the 15-domed black stone Choto Sona Mosque and taste roasted Kalai ruti with spicy duck curry.'
  },
  {
    id: 'joypurhat',
    divisionId: 'rajshahi',
    name: 'Joypurhat',
    nameBn: '????????',
    hq: 'Joypurhat',
    area: '965 km²',
    population: '1.0 Million',
    rivers: ['Chhoto Jamuna', 'Tulshiganga', 'Harabati'],
    landmarks: ['Hinda Kasba Shahi Mosque', 'Pahar Parpur Border Vista', 'Nandail Dighi', 'Lockma Rajbari'],
    delicacy: 'Joypurhat Sugar & Sugarcane Gur, Chhoto Jamunar Fish',
    heritage: 'Ancient sugar hub and limestone deposits; Hinda Kasba mosque featuring pristine white Persian domes.',
    touristTips: 'Tour the picturesque floral domes of Hinda-Kasba mosque and ancient Nandail water reservoir.'
  },

  // KHULNA DIVISION (10 Districts)
  {
    id: 'khulna',
    divisionId: 'khulna',
    name: 'Khulna',
    nameBn: '?????',
    hq: 'Khulna',
    area: '4,394 km²',
    population: '2.5 Million',
    rivers: ['Rupsha', 'Bhairab', 'Pasur'],
    landmarks: ['Sundarbans Karamjal Wildlife Center', 'Khan Jahan Ali Rupsha Bridge', 'Khulna University Campus', 'Gollamari Memorial'],
    delicacy: 'Chui Jhal Spicy Beef & Mutton, Sundarbans Raw Wild Honey, Tiger Prawns (Galda Chingri)',
    heritage: 'Southern industrial capital; gateway to the UNESCO World Heritage Sundarbans Mangrove Reserve.',
    touristTips: 'Dine at Khulnas famous Abbas Hotel or Chuknagar to taste authentic slow-cooked Chui Jhal spicy beef.'
  },
  {
    id: 'jashore',
    divisionId: 'khulna',
    name: 'Jashore',
    nameBn: '????',
    hq: 'Jashore',
    area: '2,606 km²',
    population: '3.0 Million',
    rivers: ['Bhairab', 'Kopotakkho', 'Chitra'],
    landmarks: ['Gadkhali Flower Capital (Rose & Tulip Hub)', 'Michael Madhusudan Dutt Memorial (Sagardari)', 'Collectorate Building', 'Jessore Airport (Historic 1942 WWII Base)'],
    delicacy: 'Jashore Khejur Gur (Date Palm Jaggery Patali), Jamtolar Sweet',
    heritage: 'First district of Bangladesh to be liberated from Pakistani occupation on December 7, 1971; birthplace of epic poet Madhusudan Dutt.',
    touristTips: 'Visit Gadkhali early morning to see millions of freshly plucked roses, gerberas, and orchids being traded in color markets.'
  },
  {
    id: 'bagerhat',
    divisionId: 'khulna',
    name: 'Bagerhat',
    nameBn: '????????',
    hq: 'Bagerhat',
    area: '3,959 km²',
    population: '1.6 Million',
    rivers: ['Pasur', 'Baleshwar', 'Madhumati'],
    landmarks: ['Sixty Dome Mosque (UNESCO World Heritage)', 'Shrine of Khan Jahan Ali (Dighi with sacred crocodiles)', 'Singair Mosque', 'Nine Dome Mosque', 'Sundarbans Katka Beach'],
    delicacy: 'Shrimp Curry (Bagda Chingri), Bagerhat Coconut Pitha',
    heritage: '15th-century Khalifatabad mosque city founded by Sufi general Khan Jahan Ali, inscribed by UNESCO as World Heritage.',
    touristTips: 'Marvel at the 77 low brick domes of Sixty Dome Mosque and observe the legendary marsh crocodiles of Khan Jahan Ali Dighi.'
  },
  {
    id: 'satkhira',
    divisionId: 'khulna',
    name: 'Satkhira',
    nameBn: '?????????',
    hq: 'Satkhira',
    area: '3,858 km²',
    population: '2.1 Million',
    rivers: ['Ichamati', 'Kobadak', 'Kholpetua', 'Hariabhanga'],
    landmarks: ['Sundarbans Munshiganj Forest Range', 'Jessoreshwari Kali Temple (Shakti Peeth)', 'Nalta Sharif Shrine', 'Mozaffar Garden'],
    delicacy: 'Satkhirar Sandesh & Pure Ghee, Sundarbans Khalsi Honey, Tiger Shrimp',
    heritage: 'Historic kingdom of Maharaja Pratapaditya of Bengal Baro Bhuiyans; home to Sundarbans western deep jungle creeks.',
    touristTips: 'Take a boat cruise into the Sundarbans forest canopy from Munshiganj Satkhira gateway.'
  },
  {
    id: 'kushtia',
    divisionId: 'khulna',
    name: 'Kushtia',
    nameBn: '????????',
    hq: 'Kushtia',
    area: '1,608 km²',
    population: '2.0 Million',
    rivers: ['Padma', 'Garai', 'Kumar', 'Kaliganga'],
    landmarks: ['Lalon Shah Mazar (Chheuriya)', 'Rabindranath Tagore Shilaidaha Kuthibari', 'Mir Mosharraf Hossain Memorial', 'Hardinge Bridge'],
    delicacy: 'Tiler Khaja (Sesame Crunch Sweet), Kulfi Malai',
    heritage: 'Cultural heart of Baul philosophy and mystic saint Fakir Lalon Shah; Tagore composed many Nobel-winning Gitanjali verses here.',
    touristTips: 'Attend the mystical Lalon Dol Purnima music festival in Chheuriya where thousands of Bauls perform all night.'
  },
  {
    id: 'jhenaidah',
    divisionId: 'khulna',
    name: 'Jhenaidah',
    nameBn: '???????',
    hq: 'Jhenaidah',
    area: '1,964 km²',
    population: '1.9 Million',
    rivers: ['Kobadak', 'Begabati', 'Chitra', 'Kumar'],
    landmarks: ['Naldanga Rajbari', 'Miyar Dalan Heritage Mansion', 'Johurpur Ancient Baobab Tree', 'Pagla Kanai Shrine'],
    delicacy: 'Jhenaidah Banana, Peda, Khejur Gur',
    heritage: 'Land of folk mystic lyricist Pagla Kanai and mathematician Kazi Motahar Hossain; historic indigo resistance movements.',
    touristTips: 'Admire the centuries-old African Baobab tree and the ruins of Naldanga Temple complex.'
  },
  {
    id: 'magura',
    divisionId: 'khulna',
    name: 'Magura',
    nameBn: '??????',
    hq: 'Magura',
    area: '1,048 km²',
    population: '1.0 Million',
    rivers: ['Gorai', 'Madhumati', 'Nabaganga', 'Fatki'],
    landmarks: ['Siddheswari Math', 'Raja Sitaram Ray Palace Ruins', 'Khatlagari Bil Waterfront', 'Magura Town Gateway'],
    delicacy: 'Magurar Sandesh, Sweet Curd, Madhumati Fresh Water Fish',
    heritage: 'Homeland of world-renowned all-rounder cricketer Shakib Al Hasan; historic kingdom of Raja Sitaram Ray.',
    touristTips: 'Tour the ancient terracotta Siddheswari temple in Mohammadpur alongside the Gorai river.'
  },
  {
    id: 'chuadanga',
    divisionId: 'khulna',
    name: 'Chuadanga',
    nameBn: '??????????',
    hq: 'Chuadanga',
    area: '1,170 km²',
    population: '1.2 Million',
    rivers: ['Mathabhanga', 'Bhairab', 'Chitra', 'Nabaganga'],
    landmarks: ['Carew & Co. Historic Distillery & Sugar Mills (1938)', 'Gholdari Shahi Mosque (1006 AD)', 'Darshana Border Outpost'],
    delicacy: 'Chhana Sweets, Pure Cane Sugar Jaggery, Mathabhanga Fish',
    heritage: 'Carew & Co established in 1938 is the oldest organic distillery in the subcontinent; historic first provisional capital of 1971.',
    touristTips: 'Tour the grand industrial heritage architecture of Carew & Co compound in Darshana.'
  },
  {
    id: 'meherpur',
    divisionId: 'khulna',
    name: 'Meherpur',
    nameBn: '????????',
    hq: 'Meherpur',
    area: '751 km²',
    population: '0.7 Million',
    rivers: ['Bhairab', 'Mathabhanga', 'Kazla'],
    landmarks: ['Mujibnagar Memorial Complex (Birthplace of Bangladesh Government)', 'Amjhupi Indigo Kuthi', 'Bhatpara Nilkuthi'],
    delicacy: 'Meherpur Sabri Banana, Kalo Jamun, Sweet Mangoes',
    heritage: 'On April 17, 1971, the first government of Independent Bangladesh took oath at Baidyanathtala (now Mujibnagar).',
    touristTips: 'Explore the 23-pillar Mujibnagar Monument representing 23 years of Pakistani struggle, with life-size historic war dioramas.'
  },
  {
    id: 'narail',
    divisionId: 'khulna',
    name: 'Narail',
    nameBn: '?????',
    hq: 'Narail',
    area: '990 km²',
    population: '0.8 Million',
    rivers: ['Chitra', 'Nabaganga', 'Madhumati', 'Afra'],
    landmarks: ['SM Sultan Bengal Charit Art Gallery & House', 'Niribili Picnic Spot', 'Chitra River Boat Race Center'],
    delicacy: 'Chitra River Crab, Milk Sandesh, Narail Pitha',
    heritage: 'Birthplace of globally acclaimed master painter SM Sultan, whose gigantic canvases captured the strength of Bengali peasantry.',
    touristTips: 'Visit SM Sultan Memorial Gallery on the Chitra riverbank to see his original massive oil paintings and preserved boat Shishu Swarga.'
  }
];
